spring:
    redis:
        host: ENC(P3YjHdhWti/KTkkkALOX0DpePX5ggUQjZwVW3nhbEBjgABU3jssR97QqfUJBifzG)
        port: ENC(F3TcJA4kzaDJbZOC4WS+20C9WFOteHk+7/g1KZPz84CD6GoP/knE2BNwLkPteFMC)
        password: ENC(tjVfDITYYVe7uJnI9knJ8Qo1Me5oZmHVhVLBBUwNwh0ZBMGxk9b6B806RtcmGhwN)
    data:
        mongodb:
            uri: ENC(VqC8xtO6XZaslRRr09j3B6bfrcUHLgXdi9+wEGBCukp+mLvbIr1iZRo2xMrM4i11/JJO3gw58L6KSOpOc1h133YP6qJh/P4v0gFCzLGmv40=)

logging.level.org.springframework.boot.autoconfigure: ERROR

secret:
    property: ENC(dpl9kYQl7FmW3mbfl1E/6xZLgowsZIq0s/KI5NzZgBVdQkv4qpsFuSSP2Ort5Uo4)

jasypt:
    encryptor:
        bean: encryptorBean
        algorithm: PBEWITHHMACSHA512ANDAES_256
        ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator


cxf:
   path: /ws