spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 5000
        database: 0
    data:
        mongodb:
        uri: mongodb://test:123456@127.0.0.1:27017/test

logging.level.org.springframework.boot.autoconfigure: ERROR

secret:
    property: ENC(dpl9kYQl7FmW3mbfl1E/6xZLgowsZIq0s/KI5NzZgBVdQkv4qpsFuSSP2Ort5Uo4)

jasypt:
    encryptor:
        bean: encryptorBean
        algorithm: PBEWITHHMACSHA512ANDAES_256
        ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator


cxf:
   path: /ws

logging:
    config: classpath:logback-spring.xml