spring:
    redis:
        host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 5000
        database: 0
    data:
        mongodb:
        uri: mongodb://test:123456@127.0.0.1:27017/test


logging:
    config: classpath:logback-spring.xml

# 自定义加密 ddd
secret:
    property: ENC(mwgA94JBb9h0EaV9hST02ZglcX6C9Qv/ZqplC0CNnjPNKNFZyjTdl9kjpxoWFe97)
# 加密
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}
        algorithm: PBEWITHHMACSHA512ANDAES_256

# web service tool cxf
cxf:
   path: /ws
